import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export const metadata = {
  title: 'My Blog | サイト名',
  description: 'このブログは Next.js と Sanity で構築されています。',
  openGraph: {
    title: 'My Blog | サイト名',
    description: 'このブログは Next.js と Sanity で構築されています。',
    url: 'https://example.com',
    siteName: 'My Blog',
    images: [
      {
        url: 'https://luzzblog.com/ogp.png',
        width: 1200,
        height: 630,
      },
    ],
    locale: 'ja_JP',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'My Blog | サイト名',
    description: 'このブログは Next.js と Sanity で構築されています。',
    images: ['https://example.com/ogp.png'],
  },
}
